.PATH: ./src/python/v6mig_autoconfig
SRC_DIR = ${RELSRCTOP}/python/v6mig_autoconfig
PYTHON_PKG_NAME=v6mig_autoconfig
PYTHON_MODULE_BASE=${SRC_DIR}
PYTHON_SCRIPT_BASE=${SRC_DIR}

PYTHON_MODULE_SRCS_SUBPATH ?= .



CFLAGS += \
	-I./src/python/v6mig_autoconfig \

LDADD_LAST += \

CFLAGS +=

LDFLAGS +=

.include <bsd.python.mk>
